import React, {createContext, useCallback, useContext, useEffect, useMemo, useState} from 'react';
import {ActivityIndicator, Alert, FlatList, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import {NavigationContainer, DarkTheme} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import * as api from './src/api';
import {colors} from './src/theme';
import {taskStateColor} from './src/utils';
import type {Approval, Device, Repository, Task, TaskLog} from './src/types';

type AppContextValue = {machines: Device[]; selected: Device | null; select: (d: Device) => void; reload: () => Promise<void>; live: boolean};
const AppContext = createContext<AppContextValue>(null as never);
const Stack = createNativeStackNavigator();
const Tabs = createBottomTabNavigator();

const Button = ({title, onPress, danger, disabled}: {title: string; onPress: () => void; danger?: boolean; disabled?: boolean}) => <Pressable disabled={disabled} onPress={onPress} style={[s.button, danger && s.danger, disabled && s.disabled]}><Text style={s.buttonText}>{title}</Text></Pressable>;
const Empty = ({children}: {children: React.ReactNode}) => <View style={s.empty}><Text style={s.muted}>{children}</Text></View>;
const stateColor = taskStateColor;

function Login({onDone}: {onDone: () => void}) {
  const [server, setServer] = useState(api.getBaseUrl()), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [busy, setBusy] = useState(false), [isRegister, setRegister] = useState(false);
  const submit = async () => { try { setBusy(true); api.setBaseUrl(server); isRegister ? await api.register(email, password) : await api.login(email, password); onDone(); } catch (e) { Alert.alert('Could not sign in', String(e instanceof Error ? e.message : e)); } finally { setBusy(false); } };
  return <SafeAreaView style={s.center}><StatusBar style="light"/><Text style={s.logo}>AgentDeck</Text><Text style={s.tagline}>Your coding agents, wherever you are.</Text><View style={s.card}><Text style={s.label}>Relay server</Text><TextInput autoCapitalize="none" value={server} onChangeText={setServer} style={s.input}/><Text style={s.label}>Email</Text><TextInput autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} style={s.input}/><Text style={s.label}>Password</Text><TextInput secureTextEntry value={password} onChangeText={setPassword} style={s.input}/><Button disabled={busy || !email || password.length < 12} title={busy ? 'Connecting…' : isRegister ? 'Create account' : 'Sign in'} onPress={submit}/><Pressable onPress={() => setRegister(!isRegister)}><Text style={s.link}>{isRegister ? 'Already registered? Sign in' : 'First time? Create account'}</Text></Pressable></View></SafeAreaView>;
}

function MachineHeader() {
  const {machines, selected, select, live} = useContext(AppContext);
  return <View style={s.header}><View><Text style={s.eyebrow}>MACHINE</Text><Text style={s.title}>{selected?.name || 'No laptop registered'}</Text></View><View style={s.row}>{machines.map(machine => <Pressable key={machine.id} onPress={() => select(machine)} style={[s.pill, selected?.id === machine.id && s.pillActive]}><View style={[s.dot, {backgroundColor: machine.online ? colors.primary : colors.muted}]}/><Text style={s.pillText}>{machine.label}</Text></Pressable>)}</View><Text style={s.tiny}>{live ? 'Live connection' : 'Reconnecting…'}</Text></View>;
}

function Machines() {
  const {machines, selected, select, reload} = useContext(AppContext);
  return <SafeAreaView style={s.page}><MachineHeader/><FlatList data={machines} refreshControl={<RefreshControl refreshing={false} onRefresh={reload}/>} keyExtractor={x => x.id} ListEmptyComponent={<Empty>Register a laptop with the agentdeck CLI.</Empty>} renderItem={({item}) => <Pressable onPress={() => select(item)} style={[s.card, selected?.id === item.id && s.selectedCard]}><View style={s.between}><Text style={s.cardTitle}>{item.name}</Text><Text style={{color: item.online ? colors.primary : colors.muted}}>{item.online ? '● Online' : '○ Offline'}</Text></View><Text style={s.muted}>{item.label} · {item.default_agent}</Text><Text style={s.tiny}>{JSON.stringify(item.metadata_json.agents || {})}</Text></Pressable>}/></SafeAreaView>;
}

function NewTask({navigation}: any) {
  const {selected} = useContext(AppContext); const [repos, setRepos] = useState<Repository[]>([]), [repo, setRepo] = useState<Repository | null>(null), [prompt, setPrompt] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { selected && api.repositories(selected.id).then(value => {setRepos(value); setRepo(value[0] || null);}).catch(e => Alert.alert('Repositories', e.message)); }, [selected?.id]);
  const submit = async () => { if (!selected || !repo) return; try {setBusy(true); const task = await api.createTask({device_id: selected.id, repository_id: repo.id, prompt, agent: selected.default_agent, idempotency_key: `${Date.now()}-${Math.random()}`}); setPrompt(''); navigation.navigate('Session', {taskId: task.id});} catch(e) {Alert.alert('Task not sent', e instanceof Error ? e.message : String(e));} finally {setBusy(false);} };
  return <SafeAreaView style={s.page}><MachineHeader/><ScrollView contentContainerStyle={s.content}><Text style={s.section}>Repository</Text><View style={s.wrap}>{repos.map(item => <Pressable key={item.id} onPress={() => setRepo(item)} style={[s.pill, repo?.id === item.id && s.pillActive]}><Text style={s.pillText}>{item.name}</Text></Pressable>)}</View>{!repos.length && <Empty>No allowlisted repositories reported by this laptop.</Empty>}<Text style={s.section}>What should the agent do?</Text><TextInput multiline value={prompt} onChangeText={setPrompt} placeholder="Open the project, inspect failing tests, fix the issue and run tests." placeholderTextColor={colors.muted} style={[s.input, s.composer]}/><Button title={busy ? 'Dispatching…' : `Run with ${selected?.default_agent || 'agent'}`} disabled={busy || !selected?.online || !repo || !prompt.trim()} onPress={submit}/></ScrollView></SafeAreaView>;
}

function History({navigation}: any) {
  const {selected} = useContext(AppContext); const [items, setItems] = useState<Task[]>([]), [loading, setLoading] = useState(false);
  const load = useCallback(async () => {if (!selected) return; setLoading(true); try {setItems(await api.tasks(selected.id));} finally {setLoading(false);}}, [selected?.id]); useEffect(() => {load();}, [load]);
  return <SafeAreaView style={s.page}><MachineHeader/><FlatList data={items} onRefresh={load} refreshing={loading} keyExtractor={x=>x.id} ListEmptyComponent={<Empty>No task history yet.</Empty>} renderItem={({item})=><Pressable style={s.card} onPress={()=>navigation.navigate('Session',{taskId:item.id})}><View style={s.between}><Text numberOfLines={2} style={[s.cardTitle,{flex:1}]}>{item.prompt}</Text><Text style={{color:stateColor(item.state)}}>{item.state}</Text></View><Text style={s.tiny}>{new Date(item.created_at).toLocaleString()}</Text></Pressable>}/></SafeAreaView>;
}

function Session({route}: any) {
  const taskId = route.params.taskId as string, [task,setTask]=useState<Task|null>(null),[entries,setEntries]=useState<TaskLog[]>([]),[input,setInput]=useState('');
  const load=useCallback(async()=>{const all=await api.tasks(); const found=all.find(x=>x.id===taskId); if(found)setTask(found); setEntries(await api.logs(taskId));},[taskId]); useEffect(()=>{load(); const stop=api.connectEvents(message=>{if(message.payload.task_id===taskId)load();}); return stop;},[load]);
  return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content}><View style={s.between}><Text style={[s.title,{color:stateColor(task?.state||'QUEUED')}]}>{task?.state||'Loading…'}</Text>{task && !['COMPLETED','FAILED','CANCELLED'].includes(task.state)&&<Button danger title="Stop" onPress={()=>api.cancelTask(taskId).then(load)}/>}</View><Text style={s.prompt}>{task?.prompt}</Text>{entries.map(entry=><View key={entry.sequence} style={s.log}><Text style={s.logKind}>{entry.stream.toUpperCase()}</Text><Text selectable style={s.logText}>{entry.text || JSON.stringify(entry.payload)}</Text></View>)}{task?.error&&<Text style={s.error}>{task.error}</Text>}{task?.result?.diff&&<><Text style={s.section}>Git diff</Text><Text selectable style={s.diff}>{task.result.diff}</Text></>}<Text style={s.section}>Send follow-up / paste error</Text><TextInput multiline value={input} onChangeText={setInput} style={[s.input,{minHeight:90}]}/><Button disabled={!input.trim()} title="Send to session" onPress={()=>api.sendInput(taskId,input).then(()=>setInput('')).catch(e=>Alert.alert('Could not send',e.message))}/></ScrollView></SafeAreaView>;
}

function ApprovalsScreen() { const [items,setItems]=useState<Approval[]>([]); const load=()=>api.approvals().then(setItems).catch(()=>{}); useEffect(()=>{void load();},[]); return <SafeAreaView style={s.page}><Text style={[s.title,s.content]}>Approvals</Text><FlatList data={items} keyExtractor={x=>x.id} ListEmptyComponent={<Empty>No actions need approval.</Empty>} renderItem={({item})=><View style={s.card}><Text style={s.cardTitle}>{item.action.replaceAll('_',' ')}</Text><Text style={s.muted}>{JSON.stringify(item.details)}</Text><View style={s.row}><Button title="Approve" onPress={()=>api.decideApproval(item.id,true).then(load)}/><Button danger title="Deny" onPress={()=>api.decideApproval(item.id,false).then(load)}/></View></View>}/></SafeAreaView>; }
function Settings({onLogout}:{onLogout:()=>void}) {return <SafeAreaView style={s.page}><View style={s.content}><Text style={s.title}>Settings</Text><Text style={s.label}>Relay</Text><Text style={s.card}>{api.getBaseUrl()}</Text><Button danger title="Sign out" onPress={()=>api.setTokens(null).then(onLogout)}/></View></SafeAreaView>}

function Main({onLogout}:{onLogout:()=>void}) { const [machines,setMachines]=useState<Device[]>([]),[selected,setSelected]=useState<Device|null>(null),[live,setLive]=useState(false); const reload=useCallback(async()=>{const value=await api.devices(); setMachines(value); setSelected(current=>value.find(x=>x.id===current?.id)||value[0]||null);},[]); useEffect(()=>{reload(); return api.connectEvents(()=>reload(),setLive);},[reload]); const context=useMemo(()=>({machines,selected,select:setSelected,reload,live}),[machines,selected,reload,live]); return <AppContext.Provider value={context}><Tabs.Navigator screenOptions={{headerShown:false,tabBarStyle:{backgroundColor:colors.panel,borderTopColor:colors.border},tabBarActiveTintColor:colors.primary,tabBarInactiveTintColor:colors.muted}}><Tabs.Screen name="Machines" component={Machines}/><Tabs.Screen name="Task" component={NewTask}/><Tabs.Screen name="History" component={History}/><Tabs.Screen name="Approvals" component={ApprovalsScreen}/><Tabs.Screen name="Settings">{()=> <Settings onLogout={onLogout}/>}</Tabs.Screen></Tabs.Navigator></AppContext.Provider> }
export default function App(){const [ready,setReady]=useState(false),[authenticated,setAuthenticated]=useState(false); useEffect(()=>{api.restoreTokens().then(value=>{setAuthenticated(!!value);setReady(true);});},[]); if(!ready)return <View style={s.center}><ActivityIndicator color={colors.primary}/></View>; return <NavigationContainer theme={{...DarkTheme,colors:{...DarkTheme.colors,background:colors.bg,card:colors.panel,text:colors.text,border:colors.border,primary:colors.primary}}}><Stack.Navigator screenOptions={{headerStyle:{backgroundColor:colors.panel},headerTintColor:colors.text}}>{!authenticated?<Stack.Screen name="Login" options={{headerShown:false}}>{()=> <Login onDone={()=>setAuthenticated(true)}/>}</Stack.Screen>:<><Stack.Screen name="Home" options={{headerShown:false}}>{()=> <Main onLogout={()=>setAuthenticated(false)}/>}</Stack.Screen><Stack.Screen name="Session" component={Session}/></>}</Stack.Navigator></NavigationContainer>}

const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.bg},center:{flex:1,backgroundColor:colors.bg,justifyContent:'center',padding:24},content:{padding:18,gap:12},logo:{fontSize:38,fontWeight:'800',color:colors.primary},tagline:{color:colors.muted,fontSize:16,marginBottom:28},header:{padding:18,borderBottomWidth:1,borderBottomColor:colors.border,gap:9},eyebrow:{fontSize:10,letterSpacing:2,color:colors.muted},title:{fontSize:24,fontWeight:'700',color:colors.text},section:{fontSize:17,fontWeight:'700',color:colors.text,marginTop:8},card:{margin:10,padding:16,borderRadius:14,backgroundColor:colors.panel,gap:8},selectedCard:{borderWidth:1,borderColor:colors.primary},cardTitle:{color:colors.text,fontSize:16,fontWeight:'600'},label:{color:colors.muted,fontSize:12,marginTop:10},input:{backgroundColor:colors.panel2,borderWidth:1,borderColor:colors.border,color:colors.text,padding:13,borderRadius:10},composer:{height:180,textAlignVertical:'top'},button:{backgroundColor:colors.primary,paddingHorizontal:16,paddingVertical:12,borderRadius:10,alignItems:'center'},danger:{backgroundColor:colors.danger},disabled:{opacity:.4},buttonText:{color:colors.bg,fontWeight:'800'},link:{color:colors.primary,textAlign:'center',padding:12},row:{flexDirection:'row',gap:8,alignItems:'center'},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},pill:{backgroundColor:colors.panel2,paddingHorizontal:12,paddingVertical:7,borderRadius:18,flexDirection:'row',alignItems:'center',gap:6},pillActive:{borderWidth:1,borderColor:colors.primary},pillText:{color:colors.text},dot:{width:7,height:7,borderRadius:4},muted:{color:colors.muted},tiny:{color:colors.muted,fontSize:11},empty:{padding:28,alignItems:'center'},prompt:{color:colors.text,fontSize:16,lineHeight:23},log:{borderLeftWidth:2,borderLeftColor:colors.border,paddingLeft:10,gap:3},logKind:{fontSize:9,color:colors.primary,fontWeight:'800'},logText:{color:colors.text,fontFamily:'monospace',fontSize:12},diff:{color:'#DCE6FF',backgroundColor:'#080C17',padding:12,fontFamily:'monospace',fontSize:11},error:{color:colors.danger},tagline2:{color:colors.muted}});
